### DISCUSSION TITLE
Mocking URL to local container

### DISCUSSION THREAD

**Discussion by DIOHz0r** [amazeeio/lagoon#2544] [Q&A]
Hello,

I need a local URL that redirects to my local Amazee environment, I tried with routes but it doesn't work. I use Lando and I have the option called proxy (https://docs.lando.dev/config/proxy.html#automatic-port-assignment) to catch the URL request and send it to the local develop appserver.

Is there something similar for the .lagoon.yml or docker-compose file?

**Comment by tobybellwood** [comment]
Hi @DIOHz0r - what are you using for local development (and what CMS?)

Our newest drupal-example-simple projects are all wired for Lando (although this has not been extensively tested for non-Drupal yet - and doesn't support node/python for example) - but it does work with php-based projects - I can find some examples if needed - we're collecting our examples at https://github.com/uselagoon/lagoon-examples

Otherwise, we recommend [pygmy](https://github.com/amazeeio/pygmy) or it's successor [pygmy-go](https://github.com/fubarhouse/pygmy-go) - which both create *.docker.amazee.io routes for local projects.

**Reply by DIOHz0r** [reply]
Hi @tobybellwood I'm using Drupal for local development. 

The project runs Lando or Amazee (with pygmy) on my local machine for development, however, I'm not able to configure a domain like _dev-service.myrealdomain.com_ on my local pc to act as a reverse proxy. Using Lando works by adding that domain to the proxy configuration of the lando.yml like this...

```yml
recipe: drupal8
config:
  framework: drupal
proxy:
    appserver:
        - dev-service.myrealdomain.com
services:
    appserver:
       webroot: docroot
       xdebug: true
       overrides:
           volumes:
             - lando/bashrc:/var/www/.bashrc
```

**Comment by serundeputy** [comment]
I'd give:

```yml
proxy:
    nginx:
        - dev-service.myrealdomain.com
```

a try; followed by a `lando rebuild -y`
