### ISSUE TITLE
Document how to create cronjobs for non-standard branch names

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/lagoon#1658]
**Describe the bug**

We have [docs](https://lagoon.readthedocs.io/en/latest/using_lagoon/lagoon_yml/#environments) that state you must use the `name` of the branch in your `.lagoon.yml` file. However it does not cover the use case where your branch has special characters in it.

Example of this 

```yaml
environments:
  'feature/long-branch-name-here':
    cronjobs:
      - name: 'drush cron --root=/app'
        schedule: '*/15 * * * *'
        command: drush cron
        service: cli
```

With the branch name `feature/long-branch-name-here` you are required to use quotes to ensure that the special characters are not evaluated in YAML.

Double quotes or single quotes will work, but single quotes are likely better to use for the docs.

**Comment by shreddedbacon** [comment]
It should be double quotes

**Comment by smlx** [comment]
YAML is just super complex. The rules for this case are [here](https://yaml.org/spec/1.2/spec.html#id2774228). These are the reserved characters which can't start a scalar without being quoted:
```
-?:,[]{}#&*!|>'"%@`
```
Also if you use a backslash it will _not_ be interpreted as an escape sequence if unquoted or single-quoted. It will _only_ be interpreted if the string is double-quoted (see [here](https://yaml.org/spec/1.2/spec.html#id2776092)).

So that example shouldn't need quoting unless there's something else odd going on.

git [limits branch naming](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html) in a pretty compatible way with yaml for shell script parseability anyway, so I don't know if this is really a problem..?

**Comment by AlexSkrypnyk** [comment]
@shreddedbacon I've used single quotes and it worked. But my branch name was is in the same format 'feature/long-branch-name-here'.

**Comment by seanhamlin** [comment]
Yeah the hyphen was throwing me off, according this [this post](http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html), you only need to escape a hyphen if it is at the beginning of a string and followed by a space.

So this is perfectly fine

```yaml
environments:
  feature/long-branch-name-here:
    cronjobs:
      - name: 'drush cron --root=/app'
        schedule: '*/15 * * * *'
        command: drush cron
        service: cli
```
