### ISSUE TITLE
Add a deployment marker when New Relic is enabled on a project

### ISSUE THREAD

**Issue by twardnw** [amazeeio/lagoon#1679]
Have Lagoon push a deploy marker for an environment if NEW_RELIC_ENABLE is true

https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments

**Comment by seanhamlin** [comment]
I like this idea.

Originally I was thinking we could write an example post-deploy snippet that people could include manually on their project. This has a lot of drawbacks, namely customers need to manually do the integration work, on every project they have (now an in the future). Instead I think:

* If New Relic is enabled **and** there is non-empty license key
* Automatically send a deployment marker cURL request during deployment

There could be an opt-out environment variable called `NEWRELIC_DEPLOYMENT_MARKER_ENABLED` to which would need to be set to `false` to disable this integration.

### Code snippet needed

According to the [docs](https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/):

```
curl -X POST "https://api.newrelic.com/v2/applications/$APP_ID/deployments.json" \
     -H "Api-Key:$API_KEY" \
     -i \
     -H "Content-Type: application/json" \
     -d \
"{
  \"deployment\": {
    \"revision\": \"$GIT_HASH\",
    \"changelog\": \"$deployedtag deployed to $site.$targetenv\",
    \"description\": \"$deployedtag deployed to $site.$targetenv\",
    \"user\": \"$username\",
    \"timestamp\": \"2019-10-08T00:15:36Z\"
  }
}"
```

**Comment by Schnitzel** [comment]
I'm not sure if I would do this fully automated, mostly because teams might have different ideas of when this marker should be sent out (at the very end? in the middle of all post rollout tasks? etc)

But I do think we should make it easier for teams to use this. the post rollout yaml structure is actually built for this, so we could do something like this:

```
tasks:
  post-rollout:
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - newrelicDeploymentMarker
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
```

so basically this `run` in the `post-rollout` is a specific task type, while `newrelicDeploymentMarker` is another one that will automatigically find the newrelic api keys and knows how to create a deploymentmarker for Newrelic.

This would then also allow to do something like:

```
tasks:
  post-rollout:
    - newrelicDeploymentMarker
        changelog: I'm the change
        description: triggered from lagoon
```

basically allowing teams to change the payload of the deployment marker without any curl escaping issues, etc.
