### ISSUE TITLE
Multiline cron commands failing deployments in k8s

### ISSUE THREAD

**Issue by thom8** [amazeeio/lagoon#2527]
# Describe the bug

Lagoon builds fail when defining a multiline cronjob command.

## To Reproduce

1. Define a cronjob with a multiline command

```
    cronjobs:
      - name: multiline cron command
        schedule: "15 1 * * *"
        command: |-
            echo "multiline \
            cron command"
        service: cli
```

2. Deploy the environment which contains the cronjob
3. See build error.

```
nativeCronjobs:
multiline-cron-command:
schedule: 15 1 * * *
command: |-
echo "multiline \
cron command"
inPodCronjobs: ""
+++ [[ -n image: ""
imagePullPolicy: Always
imagePullSecrets: [] ]]
+++ SERVICE_NAME_IMAGE=cli
+++ SERVICE_NAME_IMAGE_HASH=harbor-nginx-lagoon-master.ch.amazee.io/drupal9-example-simple/cron-debug/cli@sha256:792030cb7f375633bb01aefae4e67f7b72ab3a16aff1fa8e711f3603d67a8753
+++ cat /kubectl-build-deploy/cli-values.yaml
+++ helm template cli /kubectl-build-deploy/helmcharts/cli-persistent -f /kubectl-build-deploy/values.yaml -f /kubectl-build-deploy/cli-values.yaml [... logs truncated ...]
Error: YAML parse error on cli-persistent/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 83: could not find expected ':'
```

## Expected behavior

Mulitline commands defined in YAML with valid syntax are converted to valid commands for helm to create cronjob objects. 

## Workarounds

You can use YAML syntax `>` which folds multiple lines into a single line command.

```
    cronjobs:
      - name: multiline cron command
        schedule: "15 1 * * *"
        command: >
            echo "first command";
            echo "second command"
        service: cli
```
